version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "selectgearmotors-documents-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bed7k0wh2a6n"
s3_prefix = "selectgearmotors-documents-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "SQSArn=\"arn:aws:sqs:us-east-1:147397866377:selectgearmotors-notifications-queue\""
